### ISSUE TITLE
[bug] typing into bits/second field when using the digital lab adjust center frequency

### ISSUE THREAD

**Issue by Dantali0n** [Dantali0n/CubicSDR#13]
when you open a digital lab demodulator and try to edit bits/second as soon as you start typing a window pops up and you start to adjust the center frequency.

**Comment by cjcliffe** [comment]
Hmm; yeah the global keyboard handler doesn't account for focus on that part yet -- I think it just needs to check whether the input panel has focus at the top of each of the global key functions in AppFrame and ignore.

**Comment by cjcliffe** [comment]
Latest push to master will fix this for you; cheers!
